export default patientDatabase = [
    { patient_name: "Thomas G. Gustafsson", room_number: "579", diagnoses: "bipolar disorder", medications: "lithium" },
    { patient_name: "Sarah M. Johnson", room_number: "312", diagnoses: "asthma", medications: "albuterol" },
    { patient_name: "Michael B. Turner", room_number: "145", diagnoses: "diabetes", medications: "metformin" },
    { patient_name: "Emily R. Clark", room_number: "221", diagnoses: "hypertension", medications: "lisinopril" },
    { patient_name: "James K. Smith", room_number: "413", diagnoses: "depression", medications: "sertraline" },
    { patient_name: "Linda A. Moore", room_number: "618", diagnoses: "osteoporosis", medications: "alendronate" },
    { patient_name: "Robert J. White", room_number: "207", diagnoses: "chronic kidney disease", medications: "losartan" },
    { patient_name: "Patricia D. Brown", room_number: "334", diagnoses: "rheumatoid arthritis", medications: "methotrexate" },
    { patient_name: "Christopher P. Hall", room_number: "529", diagnoses: "epilepsy", medications: "lamotrigine" },
    { patient_name: "Jessica L. Lee", room_number: "642", diagnoses: "anxiety disorder", medications: "diazepam" },
    { patient_name: "Mark E. Taylor", room_number: "416", diagnoses: "heart failure", medications: "carvedilol" },
    { patient_name: "Nancy H. Wilson", room_number: "298", diagnoses: "COPD", medications: "tiotropium" },
    { patient_name: "Paul C. Martinez", room_number: "523", diagnoses: "hyperlipidemia", medications: "atorvastatin" },
    { patient_name: "Karen M. Anderson", room_number: "431", diagnoses: "migraine", medications: "sumatriptan" },
    { patient_name: "Steven R. Thomas", room_number: "637", diagnoses: "psoriasis", medications: "adalimumab" },
    { patient_name: "Barbara N. Jackson", room_number: "204", diagnoses: "hypothyroidism", medications: "levothyroxine" },
    { patient_name: "Donald S. Harris", room_number: "305", diagnoses: "chronic pain", medications: "gabapentin" },
    { patient_name: "Lisa J. Martin", room_number: "521", diagnoses: "GERD", medications: "omeprazole" },
    { patient_name: "Charles F. Lee", room_number: "439", diagnoses: "multiple sclerosis", medications: "interferon beta-1a" },
    { patient_name: "Susan A. Walker", room_number: "645", diagnoses: "chronic fatigue syndrome", medications: "modafinil" },
    { patient_name: "Joseph K. Young", room_number: "211", diagnoses: "HIV/AIDS", medications: "emtricitabine/tenofovir" },
    { patient_name: "Sandra P. King", room_number: "312", diagnoses: "lupus", medications: "hydroxychloroquine" },
    { patient_name: "Brian M. Hernandez", room_number: "423", diagnoses: "Parkinson's disease", medications: "levodopa" },
    { patient_name: "Donna G. Lopez", room_number: "534", diagnoses: "ulcerative colitis", medications: "mesalamine" },
    { patient_name: "Eric T. Gonzalez", room_number: "215", diagnoses: "eczema", medications: "betamethasone" },
    { patient_name: "Maria A. Perez", room_number: "426", diagnoses: "endometriosis", medications: "leuprolide" },
    { patient_name: "George B. Lewis", room_number: "637", diagnoses: "hepatitis C", medications: "sofosbuvir" },
    { patient_name: "Betty E. Clark", room_number: "728", diagnoses: "chronic sinusitis", medications: "fluticasone" },
    { patient_name: "Frank M. Rodriguez", room_number: "329", diagnoses: "fibromyalgia", medications: "pregabalin" },
    { patient_name: "Amy L. Walker", room_number: "438", diagnoses: "asthma", medications: "fluticasone/salmeterol" },
    { patient_name: "John R. Scott", room_number: "539", diagnoses: "Type 1 diabetes", medications: "insulin" },
    { patient_name: "Megan D. Adams", room_number: "216", diagnoses: "Celiac disease", medications: "gluten-free diet" },
    { patient_name: "Ronald W. Baker", room_number: "427", diagnoses: "ankylosing spondylitis", medications: "infliximab" },
    { patient_name: "Laura T. Mitchell", room_number: "538", diagnoses: "chronic bronchitis", medications: "salmeterol" },
    { patient_name: "Daniel P. Edwards", room_number: "219", diagnoses: "ADHD", medications: "methylphenidate" },
    { patient_name: "Rebecca J. Carter", room_number: "330", diagnoses: "chronic pancreatitis", medications: "pancrelipase" },
    { patient_name: "Anthony G. Ramirez", room_number: "441", diagnoses: "psoriatic arthritis", medications: "etanercept" },
    { patient_name: "Karen L. Phillips", room_number: "652", diagnoses: "chronic heart failure", medications: "spironolactone" },
    { patient_name: "Larry M. Evans", room_number: "223", diagnoses: "chronic lymphocytic leukemia", medications: "ibrutinib" },
    { patient_name: "Dorothy H. Turner", room_number: "334", diagnoses: "Crohn's disease", medications: "azathioprine" },
    { patient_name: "Donald T. Parker", room_number: "545", diagnoses: "benign prostatic hyperplasia", medications: "tamsulosin" },
    { patient_name: "Nancy P. Collins", room_number: "124", diagnoses: "chronic migraines", medications: "topiramate" },
    { patient_name: "Jessica R. Stewart", room_number: "227", diagnoses: "chronic insomnia", medications: "eszopiclone" },
    { patient_name: "Matthew K. Roberts", room_number: "548", diagnoses: "chronic hepatitis B", medications: "entecavir" },
    { patient_name: "Linda L. Sanchez", room_number: "229", diagnoses: "chronic liver disease", medications: "ursodiol" },
    { patient_name: "Kevin F. Morris", room_number: "340", diagnoses: "COPD", medications: "roflumilast" },
    { patient_name: "Lisa J. Rivera", room_number: "451", diagnoses: "chronic neck pain", medications: "cyclobenzaprine" },
    { patient_name: "Barbara M. Cook", room_number: "562", diagnoses: "chronic obstructive pulmonary disease", medications: "umeclidinium" },
    { patient_name: "David J. Rogers", room_number: "234", diagnoses: "asthma", medications: "montelukast" }
];